version: '3.3'

services:
  app:
    build:
      context: ./reddit-app/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"